### ISSUE TITLE
Feature request: Route more than two inputs to VST

### ISSUE THREAD

**Issue by ESPONI** [r10s/BASS_VST#1]
For those VST that have more than two audio inputs, for example, in a compressor which expects a threshold input to make a sidechain.

**Comment by radio42** [comment]
I am not sure, if that is really ever possible?
The reason is, that the VST processing is implemented as a BASS DSP.
And a BASS DSP implementation (DSPPROC) can only modify the sample data it receives - meaning it processes the sample data 1:1 as received in the DSPPROC. The DSPPROC concept doesn't allow side-chaining. Meaning there is no concept of an asymmetric number of input and output channels (asymmetric number of input and output sample data).

**Comment by ESPONI** [comment]
ok, maybe is a major mod.
Could be a new push-put stream PROC specially designed to inject data in special inputs.

Something like we use with: BASS_Mixer_StreamAddChannel(mixer, streamA)
More or less:
dspHandler = BASS_VST_ChannelSetDSP(mixerHandler, "VST.dll")
BASS_VST_StreamAddChannel(dspHandler, streamB, ¿destinationChannelNumber?)

**Comment by radio42** [comment]
Feel free to implement something like that.
You might than contribute your results back here!

**Comment by ESPONI** [comment]
:(   :(   :(   Conceptual skills 100% but, not enough C++ skills.

**Comment by r10s** [comment]
I would also be glad to publish the changes here, however, I won't code it myself currently.
